"""
app.py
-------
Flask backend for the AI Health Symptom Predictor.

Endpoints:
  GET  /api/symptoms        -> list of all symptoms the model understands
  POST /api/predict         -> {symptoms: [...]} -> prediction + precautions + doctor
  POST /api/report          -> generates a downloadable text health report
  GET  /api/health          -> health check

Run:
  pip install -r requirements.txt
  python app.py
"""

import os
import json
from datetime import datetime

import joblib
import numpy as np
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(BASE_DIR, "model")

app = Flask(__name__)
CORS(app)

# ------------------------------------------------------------------
# Load model + artifacts at startup
# ------------------------------------------------------------------
model = joblib.load(os.path.join(MODEL_DIR, "model.pkl"))
label_encoder = joblib.load(os.path.join(MODEL_DIR, "label_encoder.pkl"))

with open(os.path.join(MODEL_DIR, "symptoms.json")) as f:
    ALL_SYMPTOMS = json.load(f)

with open(os.path.join(MODEL_DIR, "precautions.json")) as f:
    DISEASE_INFO = json.load(f)


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def vectorize_symptoms(selected_symptoms):
    """Convert a list of symptom names into the binary feature vector
    expected by the model, in the same column order used at training time."""
    return np.array([[1 if s in selected_symptoms else 0 for s in ALL_SYMPTOMS]])


def build_report_text(name, age, symptoms, prediction, confidence, info):
    lines = [
        "=" * 50,
        "        AI HEALTH SYMPTOM PREDICTOR - REPORT",
        "=" * 50,
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"Patient Name: {name or 'N/A'}",
        f"Age: {age or 'N/A'}",
        "",
        "Reported Symptoms:",
    ]
    lines += [f"  - {s.replace('_', ' ').title()}" for s in symptoms]
    lines += [
        "",
        f"Predicted Condition: {prediction}",
        f"Model Confidence: {confidence}%",
        f"Severity: {info.get('severity', 'N/A')}",
        f"Recommended Specialist: {info.get('doctor', 'N/A')}",
        "",
        "Suggested Precautions:",
    ]
    lines += [f"  - {p}" for p in info.get("precautions", [])]
    lines += [
        "",
        "-" * 50,
        "DISCLAIMER: This report is generated by a machine learning",
        "model for educational/demo purposes only. It is NOT a medical",
        "diagnosis. Please consult a licensed doctor for medical advice.",
        "-" * 50,
    ]
    return "\n".join(lines)


# ------------------------------------------------------------------
# Routes
# ------------------------------------------------------------------
@app.route("/api/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


@app.route("/api/symptoms", methods=["GET"])
def get_symptoms():
    return jsonify({"symptoms": ALL_SYMPTOMS})


@app.route("/api/predict", methods=["POST"])
def predict():
    data = request.get_json(force=True)
    symptoms = data.get("symptoms", [])

    if not symptoms:
        return jsonify({"error": "Please provide at least one symptom"}), 400

    # ignore symptoms the model doesn't know about
    valid_symptoms = [s for s in symptoms if s in ALL_SYMPTOMS]
    if not valid_symptoms:
        return jsonify({"error": "None of the provided symptoms are recognized"}), 400

    X = vectorize_symptoms(valid_symptoms)

    proba = model.predict_proba(X)[0]
    top_idx = int(np.argmax(proba))
    disease = label_encoder.inverse_transform([top_idx])[0]
    confidence = round(float(proba[top_idx]) * 100, 2)

    # top-3 possible conditions
    top3_idx = np.argsort(proba)[::-1][:3]
    top3 = [
        {
            "disease": label_encoder.inverse_transform([i])[0],
            "confidence": round(float(proba[i]) * 100, 2),
        }
        for i in top3_idx
    ]

    info = DISEASE_INFO.get(disease, {})

    return jsonify({
        "prediction": disease,
        "confidence": confidence,
        "top3": top3,
        "precautions": info.get("precautions", []),
        "doctor": info.get("doctor", "General Physician"),
        "severity": info.get("severity", "Unknown"),
    })


@app.route("/api/report", methods=["POST"])
def report():
    data = request.get_json(force=True)
    name = data.get("name")
    age = data.get("age")
    symptoms = data.get("symptoms", [])
    prediction = data.get("prediction")
    confidence = data.get("confidence")

    info = DISEASE_INFO.get(prediction, {})
    text = build_report_text(name, age, symptoms, prediction, confidence, info)

    report_path = os.path.join(BASE_DIR, "health_report.txt")
    with open(report_path, "w") as f:
        f.write(text)

    return send_file(report_path, as_attachment=True, download_name="health_report.txt")


if __name__ == "__main__":
    app.run(debug=True, port=5000)
